#! /usr/bin/python
from math import *

ninter=int (raw_imput ("Dame el numero de subintervalos para aproximar pi")
suma=0
for i in range (1,n) 
float a=(i-1)/n
float b=(i)/n
float xi=(i-0.5)/n
float fxi=(4.0/(1.0 + x*x)
print ("Subintervalo:",[a,b]  "xi:"xi  "fxi",fxi)
sum+=fxi
